### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Pabloquero** [nikhilwadibhasme/electron-edge-printer#1]
Hi, im new in this electron world, if i get this right, do i need to install electron-edge to use this features?
i need to set the page size and color of my outputs, using this means that i have to install all edge requirements ( Visual Studio 2015 redist and .NET framework 4.5. ) in the computers where i want to run the electron app, right? sorry if this is a very noob question.

Thank you!

**Comment by nikhilwadibhasme** [comment]
@Pabloquero Yes you have to install all the dependencies mentioned in package.json (npm install).
and .net framework is required for this node module as we are using the .net dll's.
If you are running on the windows OS you don't need to think as windows comes with .net framework.

I hope this will help you.I will update this with some more functions.Please let me know for further details/queries?

Regards,
Nikhil

**Comment by Pabloquero** [comment]
Hey! i have been investigating and havent found anything else that seems to work, can i send you an email with the functions i need to make to work? I need to know if its possible to do that with this (and how :P).
 Thank you!

**Comment by nikhilwadibhasme** [comment]
@Pabloquero  ok fine you can send.
